name: hisobla
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get_it: ^9.0.5
  intl: ^0.20.2

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Local Database
  shared_preferences: ^2.5.3
  path_provider: ^2.1.1

  # Utilities
  url_launcher: ^6.3.2
  share_plus: ^12.0.1

  # Ads
  google_mobile_ads: ^6.0.0

   # Notifications - YANGI
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # AI va HTTP - YANGI
  http: ^1.2.0
  
  # Charts - YANGI
  fl_chart: ^0.66.0



  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_hisobla.png"   
  adaptive_icon_background: "#ffffff"  
  adaptive_icon_foreground: "assets/images/app_logo_hisobla.png"


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo_hisobla.png
  android: true
  ios: true




flutter:

  uses-material-design: true

  assets:
    - assets/images/